import { useState, useCallback } from "react";
import { jsPDF } from "jspdf";
import { Header } from "@/components/Header";
import { FileUploadZone } from "@/components/FileUploadZone";
import { TextPanel } from "@/components/TextPanel";
import { SummaryPanel } from "@/components/SummaryPanel";
import { useToast } from "@/hooks/use-toast";

export default function Home() {
  const [fileContent, setFileContent] = useState("");
  const [fileName, setFileName] = useState("");
  const [summary, setSummary] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [isExporting, setIsExporting] = useState(false);
  const { toast } = useToast();

  const handleFileUpload = useCallback((file: File, content: string) => {
    setFileContent(content);
    setFileName(file.name);
    setSummary("");
    toast({
      title: "File uploaded",
      description: `${file.name} has been loaded successfully.`,
    });
  }, [toast]);

  const handleClear = useCallback(() => {
    setFileContent("");
    setFileName("");
    setSummary("");
  }, []);

  const handleSummarize = useCallback(async () => {
    if (!fileContent) return;
    
    setIsLoading(true);
    try {
      const response = await fetch("/api/summarize", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ content: fileContent }),
      });
      
      if (!response.ok) {
        throw new Error("Failed to generate summary");
      }
      
      const data = await response.json();
      setSummary(data.summary);
      toast({
        title: "Summary generated",
        description: "Your document has been summarized successfully.",
      });
    } catch (error) {
      toast({
        title: "Error",
        description: "Failed to generate summary. Please try again.",
        variant: "destructive",
      });
    } finally {
      setIsLoading(false);
    }
  }, [fileContent, toast]);

  const handleExportPdf = useCallback(async () => {
    if (!summary) return;
    
    setIsExporting(true);
    try {
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      const margin = 20;
      const maxWidth = pageWidth - margin * 2;
      
      doc.setFontSize(18);
      doc.setFont("helvetica", "bold");
      doc.text("AI Summary", margin, margin + 10);
      
      if (fileName) {
        doc.setFontSize(10);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(100);
        doc.text(`Source: ${fileName}`, margin, margin + 18);
        doc.setTextColor(0);
      }
      
      doc.setFontSize(11);
      doc.setFont("helvetica", "normal");
      
      const lines = doc.splitTextToSize(summary, maxWidth);
      let y = margin + 30;
      
      for (const line of lines) {
        if (y > pageHeight - margin) {
          doc.addPage();
          y = margin;
        }
        doc.text(line, margin, y);
        y += 6;
      }
      
      doc.setFontSize(8);
      doc.setTextColor(150);
      doc.text(
        `Generated by AI Notes Summarizer on ${new Date().toLocaleDateString()}`,
        margin,
        pageHeight - 10
      );
      
      doc.save(`summary-${fileName?.replace(/\.[^/.]+$/, "") || "document"}.pdf`);
      
      toast({
        title: "PDF exported",
        description: "Your summary has been saved as a PDF file.",
      });
    } catch (error) {
      toast({
        title: "Export failed",
        description: "Failed to export PDF. Please try again.",
        variant: "destructive",
      });
    } finally {
      setIsExporting(false);
    }
  }, [summary, fileName, toast]);

  const hasFile = Boolean(fileContent);
  const hasSummary = Boolean(summary);

  return (
    <div className="min-h-screen bg-background">
      <Header
        onExportPdf={handleExportPdf}
        isExporting={isExporting}
        canExport={hasSummary}
      />
      
      <main className="mx-auto max-w-7xl px-6 py-8">
        {!hasFile ? (
          <div className="flex min-h-[60vh] items-center justify-center">
            <FileUploadZone
              onFileUpload={handleFileUpload}
              isLoading={isLoading}
            />
          </div>
        ) : (
          <div className="grid gap-6 lg:grid-cols-2">
            <TextPanel
              title="Original Text"
              content={fileContent}
              fileName={fileName}
              onClear={handleClear}
            />
            <SummaryPanel
              summary={summary}
              isLoading={isLoading}
              onSummarize={handleSummarize}
              canSummarize={hasFile}
            />
          </div>
        )}
      </main>
    </div>
  );
}
